
server:
  port: 8081
  servlet:
    context-path: /appmonitor




spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    #配置h2数据库的连接地址
    url: jdbc:h2:file:./appMonitorDB
    username: sa
    password: 123123

  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      mode: always
      platform: h2
      password: 123123
      username: sa
  h2:
    console:
      path: /h2-admin
      enabled: true
      settings:
        web-allow-others: true
        web-admin-password: 123123



mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

